version: '3.3'
volumes:
  store_data: null
  db_data: null
  rabbitmq_data: null
  ldap_data: null
  ldap_config: null
  es_data: null
services:
  haproxy:
    image: 'haproxy:1.8'
    ports:
      - '80:80'
    volumes:
      - './haproxy.cfg:/opt/haproxy.conf:ro'
    entrypoint: haproxy -f /opt/haproxy.conf
    depends_on:
      - nginx
  nginx:
    image: 'nginx:1.15'
    ports:
      - '8080:8080'
    volumes:
      - './nginx.cfg:/etc/nginx/nginx.conf:ro'
    entrypoint: nginx -g 'daemon off';
    depends_on:
      - django
  django:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - 'store_data:/var/store'
      - './app:/app'
    env_file:
      - app.env
      - db.env
      - ldap.env
    depends_on:
      - db
      - rabbitmq
  db:
    image: 'postgres:9.5'
    ports:
      - '5432:5432'
    volumes:
      - 'db_data:/var/lib/postgresql/data'
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_INITDB_ARGS=--data-checksums --locale=en_US.utf8
    env_file:
      - db.env
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/data'
    env_file:
      - rabbitmq.env
  ldap:
    image: 'osixia/openldap:1.2.2'
    ports:
      - '389:389'
    volumes:
      - 'ldap_data:/var/lib/ldap'
      - 'ldap_config:/etc/ldap/slapd.d'
    env_file:
      - ldap.env
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.5.1'
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'es_data:/usr/share/elasticsearch/data'
      - './elastic.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro'
    env_file:
      - elastic.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - elk
  kibana:
    image: 'docker.elastic.co/kibana/kibana:6.5.1'
    ports:
      - '5601:5601'
    environment:
      SERVER_NAME: localhost
      SERVER_HOST: 0.0.0.0
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
    depends_on:
      - elasticsearch
    networks:
      - elk
networks:
  elk: null
